package com.example.schoolofrock;

import android.app.NotificationManager;
import android.app.PendingIntent;
import android.content.Intent;
import android.os.Bundle;

import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.snackbar.Snackbar;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;

import android.view.View;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity implements AdapterView.OnItemSelectedListener{

    // declare EditText
    EditText voterEditText;

    // declare Spinners
    Spinner songSpinner;

    // declare Strings for data input by user
    String song;
    String voter;

    // declare DBHandler
    DBHandler dbHandler;



        /**
         * This method initializes the MainActivity.
         * @param savedInstanceState a Bundle object that is passed into the onCreate
         *                           method of every Android Activity. Activities have
         *                           the ability, under special circumstances, to restore
         *                           themselves to a previous state using the data stored
         *                           in this bundle. If there is no available instance data,
         *                           the savedInstanceState will be null.
         */
        @Override
        protected void onCreate (Bundle savedInstanceState){

        // code generated by Android Studio that initializes the View
        // and ActionBar of MainActivity Activity
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        // initialize EditText
        voterEditText = (EditText) findViewById(R.id.voterEditText);

        // initialize Spinners
        songSpinner = (Spinner) findViewById(R.id.songSpinner);

        // initialize ArrayAdapter with values in year string array
        // and stylize it with style defined by simple_spinner_item
        ArrayAdapter<CharSequence> yearAdapter = ArrayAdapter.createFromResource(this, R.array.song, android.R.layout.simple_spinner_item);

        // further stylize ArrayAdapter with style defined by simple_spinner_dropdown_item
        yearAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);

        // set ArrayAdapter on Spinner
        songSpinner.setAdapter(yearAdapter);

        // set OnItemSelectedListener on Spinner
        songSpinner.setOnItemSelectedListener(this);

        // initialize DBHandler
        dbHandler = new DBHandler(this, null);

    }

        @Override
        public boolean onCreateOptionsMenu (Menu menu){
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

        public void likeSong (MenuItem menuItem) {

            voter = voterEditText.getText().toString();

            // trim Strings and see if any are equal to an empty String
            if ((song.trim().equals("")) || (voter.trim().equals(""))){
                // if any are equal to an empty String, then that means
                // required data hasn't been input, so display a toast
                Toast.makeText(this, "Please enter a name, year, and major!", Toast.LENGTH_LONG).show();
            } else {
                // if none are equal to an empty String, then that means
                // all required data has been input, so update the database
                // and display a toast
                dbHandler.likeSong(song, voter);
                Toast.makeText(this, song + " added!", Toast.LENGTH_LONG).show();
            }
        }

        //
        //
        // This would be notifaction option converted into the right variables for the app "School of Rock" but I ran out of time to fix this.
         if (currentDate.compareTo(reminderDate) > 0){
        // initialize Notification
        NotificationCompat.Builder builder = new NotificationCompat.Builder(MainActivity.this);

        // set it icon, title, and text
        builder.setSmallIcon(R.mipmap.ic_launcher);
        builder.setContentTitle();
        builder.setContentText();

        // initialize an Intent for the Main Activity
        intent = new Intent(MainActivity.this, MainActivity.class);

        // initialize a PendingIntent
        PendingIntent pendingIntent = PendingIntent.getActivity(MainActivity.this, 0, intent, PendingIntent.FLAG_UPDATE_CURRENT);

        // set the content intent of the Notification
        builder.setContentIntent(pendingIntent);

        // initialize a NotificationManager
        NotificationManager notificationManager = (NotificationManager) getSystemService(NOTIFICATION_SERVICE);

        // have the NotificationManager send the Notification
        notificationManager.notify(2142, builder.build());
    }
    @Override
    public void onItemSelected(AdapterView<?> adapterView, View view, int position, long id) {
        song = adapterView.getItemAtPosition(position).toString();
    }

    @Override
    public void onNothingSelected(AdapterView<?> adapterView) {

    }
}


